//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FichaOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ficha
    {
        public Ficha()
        {
            this.Peculiaridades = new HashSet<Peculiaridade>();
            this.PropriedadesRiquezasItensArmas = new HashSet<PropriedadeRiquezaItemArma>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public int Idade { get; set; }
        public string Classe { get; set; }
        public string Raca { get; set; }
        public int Adre { get; set; }
        public int Ataq { get; set; }
        public int Defe { get; set; }
        public int Dest { get; set; }
        public int Forc { get; set; }
        public int Inte { get; set; }
        public int Resi { get; set; }
        public int Sabe { get; set; }
        public int Velo { get; set; }
        public int Vital { get; set; }
        public int Sorte { get; set; }
        public string Nota { get; set; }
        public int Experiencia { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> MestreId { get; set; }
        public int Pontos { get; set; }
        public int PtsPeculiaridades { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Peculiaridade> Peculiaridades { get; set; }
        public virtual ICollection<PropriedadeRiquezaItemArma> PropriedadesRiquezasItensArmas { get; set; }
    }
}
