//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FichaOnline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FichaOnlineContainer : DbContext
    {
        public FichaOnlineContainer()
            : base("name=FichaOnlineContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Usuario> UsuarioSet { get; set; }
        public DbSet<Ficha> FichaSet { get; set; }
        public DbSet<Peculiaridade> PeculiaridadeSet { get; set; }
        public DbSet<Pratica> PraticaSet { get; set; }
        public DbSet<PropriedadeRiquezaItemArma> PropriedadeRiquezaItemArmaSet { get; set; }
    }
}
