//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FichaOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropriedadeRiquezaItemArma
    {
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Subtipo { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public int PesoQuantidade { get; set; }
        public int ValorDano { get; set; }
        public int FichaId { get; set; }
    
        public virtual Ficha Ficha { get; set; }
    }
}
